version: "3.9"
services:
  bedrock:
    image: itzg/minecraft-bedrock-server
    container_name: bedrock
    restart: unless-stopped
    ports:
      - 19132:19132/udp
      - 19133:19133/udp
    volumes:
      - /home/nlxdodge/servers/bedrock:/data
    stdin_open: true
    tty: true  
    environment:
      EULA: "TRUE"
      SERVER_NAME: "Korf Craft, nu met nog meer drama!"
      LEVEL_NAME: "Korf Craft"
      MAX_PLAYERS: "10"
      DIFFICULTY: "normal"
      LEVEL_SEED: "31563250179158"
      VIEW_DISTANCE: "16"
      MAX_THREADS: "10"
