version: '3.8'

services:
  reverse-proxy:
    image: traefik:v3.0
    container_name: traefik
    hostname: traefik
    user: 1000:1000
    restart: unless-stopped
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock