version: "3.8"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.file.directory=/etc/traefik"
      - "--certificatesresolvers.letsencrypt.acme.email=contact@gerbenveenhof.nl"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - acme-data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./bluemap.yml:/etc/traefik/bluemap.yml
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.gerbenveenhof.nl`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8090"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.docker.network=global"

volumes:
  acme-data:

networks:
  default:
    external:
      name: global  
