services:
  portfolio:
    image: ../../portfolio-astro
    container_name: portfolio
    restart: unless-stopped
    ports:
      - 5000:80
    labels:
      - "traefik.http.routers.portfolio.rule=Host(`test.gerbenveenhof.nl`)"
      - "traefik.http.services.portfolio.loadbalancer.server.port=5000"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.docker.network=global"
      - "traefik.enable=true"

networks:
  default:
    external:
      name: global