version: "3.8"

services:
  mc:
    image: .
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      - /home/nlxdodge/servers/minecraft:/data