version: "3.9"
services:
  notifiarr:
    image: golift/notifiarr
    container_name: notifiarr
    restart: unless-stopped
    hostname: notifiarr
    environment:
      - NOTIFIARR_API_KEY=
    ports:
      - "5454:5454"
    volumes:
      - /home/nlxdodge/configurations/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id